config/routes.rb
Rails.application.routes.draw do

  root 'home#index1'

  resources :employees #resource controller

  resources :sports_news
  get "about-us" => "pages#about_us"
  get "contact-us" => "pages#contact_us"
  get  "privacy-policy" => "pages#privacy_policy"
  get  "terms-conditions" => "pages#terms_and_conditions"

  get "user" => "login#user" 
  get "profile" => "login#profile"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :first_name, :last_name, presence: true
  validates :city, :state, :pincode, :address_line_1, :country, presence: true
end

app/models/sports_new.rb
class SportsNew < ApplicationRecord

  validates :level,:authority,:mode, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    before_action :set_employee, only: [:edit,:update,:show,:destroy]
  #index,new,create : these are employees resource actions
    def index
       @employees=Employee.all
    end  
    
    def new 
        @employee=Employee.new #create model object
    end  
    
    def create
         @employee = Employee.new(employee_params)
            if @employee.save
                redirect_to employees_path, notice: 'Employee created successfully'
            else
                render :new
            end
    end 

    def edit
        #phele employee chaiye hoga:before action iske liye hai
    end    

    def update
        #phele employee chaiye hoga
         if @employee.update(employee_params)
            redirect_to employees_path, notice: 'Employee updated successfully'
         else   
            render :edit
         end   
    end  
    
    def show
        #phele employee chaiye hoga
    end 
    
    def destroy
        #phele employee chaiye hoga
        if @employee.destroy 
            redirect_to employees_path , notice:"Employee Deleted"
        else
            render :edit
        end    

    end   
    
    private
    
    def employee_params
        params.require(:employee).permit(:first_name,:last_name,:city,:state,:pincode,:country,:address_line_1,:address_line_2)
    end   
    
    def set_employee
         @employee=Employee.find(params[:id])
     rescue ActiveRecord::RecordNotFound => error
        redirect_to employees_path , notice:error
    end    
end  

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index1 #instance method
    @title_name='I am learning ruby !'   #instance variable
    @subtitle_text='Ruby latest version 3.4.8' 
  end  
  
end  

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def user  #instance method
    @username="Ashish"

  end

  def profile
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/controllers/sports_news_controller.rb
class SportsNewsController < ApplicationController

  def index
    @sports_news=SportsNew.all
  end  

    def new
        @sports_new=SportsNew.new
    end  

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
        <h2 class="text-center">Edit Employee Information</h2>
        </div>
    </div>
    
      <!--using partials-->
     <%= render 'shared/form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
   <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
        <h2 class="text-center">Listing Employees</h2>
        </div>
    </div>
  
  <div class="text-center mb-5">
    <%= link_to "Create New Employee", new_employee_path, 
          class: "btn btn-lg text-white rounded-0 px-4 py-2 shadow-sm",
          style: "background-color: #0275c2ff;" %>
  </div>
</div>


<div class="table-responsive d-none d-lg-block">
  
  <table class="table table-bordered table-striped">
    <thead class="table-light">
      <tr>
        <th>Employee_ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>City</th>
        <th>State</th>
        <th>Pincode</th>
        <th>Country</th>
        <th>Address1</th>
        <th>Address2</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.id %></td>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.city %></td>
          <td><%= employee.state %></td>
          <td><%= employee.pincode %></td>
          <td><%= employee.country %></td>
          <td><%= employee.address_line_1 %></td>
          <td><%= employee.address_line_2 %></td>
          <td>
            <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-primary " %>
            <%= link_to 'View', employee_path(employee), class: "btn btn-info" %>
           <%= button_to 'Delete', employee_path(employee), method: :delete, onclick: "return confirm('Are you sure you want to delete this employee?');", class: "btn btn-danger", form: { class: "d-inline" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<div class="d-lg-none">
  <% @employees.each do |employee| %>
    <div class="card mb-3">
      <div class="card-body">
        <p><strong>Employee ID:</strong> <%= employee.id %></p>
        <p><strong>Name:</strong> <%= employee.first_name %> <%= employee.last_name %></p>
        <p><strong>City:</strong> <%= employee.city %></p>
        <p><strong>State:</strong> <%= employee.state %></p>
        <p><strong>Pincode:</strong> <%= employee.pincode %></p>
        <p><strong>Country:</strong> <%= employee.country %></p>
        <p><strong>Address1:</strong> <%= employee.address_line_1 %></p>
        <p><strong>Address2:</strong> <%= employee.address_line_2 %></p>
        <div class="d-flex gap-2 mt-2">
         <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-primary " %>
         <%= link_to 'View', employee_path(employee), class: "btn btn-info " %>
         <%= button_to 'Delete', employee_path(employee), method: :delete, onclick: "return confirm('Are you sure you want to delete this employee?');", class: "btn btn-danger", form: { class: "d-inline" } %>
        </div>
      </div>
    </div>
  <% end %>
</div>


</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
        <h2 class="text-center">Create New Employee</h2>
        </div>
    </div>

    <!--using partials-->
    <%= render 'shared/form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
        <h2 class="text-center">Employee Details</h2>
        <div class="row mt-5">
            <div class="col-lg-6">
                <h3 class="mb-3" >Personal Information</h3>
                <p class="lead"><strong>Employee-id:</strong><%= @employee.id%></p>
                <p class="lead"><strong>First Name:</strong><%= @employee.first_name%></p>
                 <p class="lead"><strong>Last Name:</strong><%= @employee.last_name%></p>
            </div>
            <div class="col-lg-6">
                <h3 class="mb-3" >Address Information</h3>

                 <p class="lead"><strong>City:</strong><%= @employee.city%></p>
                  <p class="lead"><strong>State:</strong><%= @employee.state%></p>
                   <p class="lead"><strong>Country:</strong><%= @employee.country%></p>
                <p class="lead"><strong>Address1:</strong><%= @employee.address_line_1%></p>
                  <p class="lead"><strong>Address2:</strong><%= @employee.address_line_2.present? ? @employee.address_line_2 : '--N/A--'%></p>
               
            </div>
         </div>  
         <%= link_to 'Back to employees', employees_path, class:"btn btn-outline-primary btn-lg rounded-0"%> 
          <%= link_to 'Edit Employees', edit_employee_path(@employee), class:"btn btn-primary btn-lg rounded-0"%> 
          
        </div>
    </div>
</div>    

app/views/home/index1.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Home</h1>
  <%= render 'shared/dummyContent'%>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hr-Saathi" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>

    <!-- Flash Message Modal -->
    <% if flash[:notice] || flash[:alert] %>
      <div class="modal fade" id="flashModal" tabindex="-1" aria-labelledby="flashModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header bg-primary text-white">
              <h5 class="modal-title" id="flashModalLabel">
                <%= flash[:notice] ? '✓ Success' : '✗ Alert' %>
              </h5>
              <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center py-4 bg-white">
              <h5><%= flash[:notice] || flash[:alert] %></h5>
            </div>
            <div class="modal-footer bg-white">
              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">OK</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="container">
      <div class="row">
           <%= yield %>
      </div>
    </div>

    <%= render 'shared/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script>
     
      document.addEventListener('DOMContentLoaded', function() {
        const flashModal = document.getElementById('flashModal');
        if (flashModal) {
          const modal = new bootstrap.Modal(flashModal);
          modal.show();
          
          
          setTimeout(function() {
            modal.hide();
          }, 4000);
        }
      });
    </script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </body>
</html>

app/views/login/profile.html.erb
<h1>Profile is here !</h1>
 <%= render 'shared/links'%>

app/views/login/user.html.erb
<h1><%= @username %> is here</h1>

<%= link_to 'profile' , profile_path%>
 <%= render 'shared/links'%>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">About HR-Saathi</h1>
  <%= render 'shared/dummyContent'%>
</div>  
  

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Contact</h1>
  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div>
</div> 

app/views/pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Privacy Policy</h1>
  <%= render 'shared/dummyContent'%>
</div> 

app/views/pages/terms_and_conditions.html.erb
<h1>Pages#terms_and_conditions</h1>
<p>Find me in app/views/pages/terms_and_conditions.html.erb</p>

 <%= link_to 'About-Us', about_us_path, target:"_blank", data: { name: "about_us", resources: "pages" }%>

 <%= link_to 'Contact-Us' , contact_us_path%>

 <%= link_to 'privacy', privacy_policy_path%>

 <%= link_to 'terms_and_conditions' , terms_conditions_path, target:'_blank'%>

app/views/shared/_dummyContent.html.erb
<div class="row justify-content-center">
  <div class="col-lg-8 col-md-10">
    <p class="lead text-muted">
   It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
    </p>

    <p class="lead text-muted">
     It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

    <p class="lead text-muted">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout...
    </p>
  </div>
</div>

app/views/shared/_footer.html.erb
    <!-- footer -->
<footer class="py-lg-8 py-5">
    <div class="container">
        <div class="row  justify-content-center text-center  ">
            <div class="col-12 col-md-12 col-xl-8 px-0 ">
                <nav class="nav nav-footer justify-content-center">
                    <%= link_to 'Home' , root_path , class:"nav-link"%>
                    <%= link_to 'About' , about_us_path , class:"nav-link"%>
                    <%= link_to 'Contact' , contact_us_path , class:"nav-link"%>
                    <%= link_to 'T&C' , terms_conditions_path , class:"nav-link"%>
                    <%= link_to 'Employees', employees_path , class:"nav-link"%>
                </nav>
            </div>

        </div>
    </div>
</footer>

app/views/shared/_form.html.erb
<%= form_with model: employee, local: true do |form| %>
        <div class="row">


     <!-- <% if @employee.errors.any? %>
                    <div class="col-lg-12">
                        <p class="lead">Please fix errors below</p>
                        <% @employee.errors.full_messages.each do |message|%>   
                            <p class="text-danger"><%= message%></p>
                        <%end%>
                    </div>
            <% end %>
     -->
            <div class="col-lg-4">
                <div class="form-group">
                <%= form.label :first_name, class: "mb-2" %>
                <%= form.text_field :first_name, class: "form-control form-control-lg rounded-0" %>
                 <% @employee.errors.full_messages_for(:first_name).each do |message|%> 
                  <p class="text-danger"><%= message%></p>
                 <% end%>  
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :last_name, class: "mb-2"%>
                    <%= form.text_field :last_name, class: "form-control form-control-lg rounded-0" %>
                      <% @employee.errors.full_messages_for(:last_name).each do |message|%> 
                  <p class="text-danger"><%= message%></p>
                 <% end%>  
                </div>   
            </div>   

        </div>

        <div class="row">

             <div class="col-lg-4 mt-2">
                <div class="form-group">
                <%= form.label :pincode, class: "mb-2" %>
                <%= form.text_field :pincode, class: "form-control form-control-lg rounded-0" %>
                  <% @employee.errors.full_messages_for(:pincode).each do |message|%> 
                  <p class="text-danger"><%= message%></p>
                 <% end%>  
                </div>
            </div>

            <div class="col-lg-3 mt-2">
                <div class="form-group">
                <%= form.label :city, class: "mb-2" %>
                <%= form.text_field :city, class: "form-control form-control-lg rounded-0" %>
                <% @employee.errors.full_messages_for(:city).each do |message|%>
                <p class="text-danger"><%= message%></p>
                <%end%>
                </div>
            </div>

            <div class="col-lg-4 mt-2">
                <div class="form-group">
                <%= form.label :state, class: "mb-2" %>
                <%= form.text_field :state, class: "form-control form-control-lg rounded-0" %>
                 <% @employee.errors.full_messages_for(:state).each do |message|%>
                <p class="text-danger"><%= message%></p>
                <%end%>
                </div>
            </div>

            <div class="col-lg-4 mt-2">
                <div class="form-group">
                <%= form.label :country, class: "mb-2" %>
                <%= form.text_field :country, class: "form-control form-control-lg rounded-0" %>
                 <% @employee.errors.full_messages_for(:country).each do |message|%>
                <p class="text-danger"><%= message%></p>
                <%end%>
                </div>
            </div>

             <div class="col-lg-4 mt-2">
                <div class="form-group">
                <%= form.label :address_line_1, class: "mb-2" %>
                <%= form.text_field :address_line_1, class: "form-control form-control-lg rounded-0" %>
                 <% @employee.errors.full_messages_for(:address_line_1).each do |message|%>
                <p class="text-danger"><%= message%></p>
                <%end%>
                </div>
            </div>

             <div class="col-lg-4 mt-2">
                <div class="form-group">
                <%= form.label :address_line_2, class: "mb-2" %>
                <%= form.text_field :address_line_2, class: "form-control form-control-lg rounded-0" %>
                </div>
            </div>

            
        </div>

        <div class="row">

             <div class="col-lg-12 mt-5">
                    <div class="text-center">
                        <%= form.submit class:"btn btn-primary btn-lg rounded-0"%>
                        <%= link_to 'Back to Employees' , employees_path, class:"btn btn-outline-primary btn-lg rounded-0"%>
                    </div>
             </div>
        </div>   
    
    <% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "HR-Saathi", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link ms-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_us_path, class: "nav-link ms-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_us_path, class: "nav-link ms-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "T&C", terms_conditions_path, class: "nav-link ms-3" %>
        </li>
         <li class=" nav nav-item nav-underline">
          <%= link_to "Employees", employees_path, class: "nav-link ms-3" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<%= link_to 'About-Us', about_us_path,  style:'color:blue;',target:"_blank", data: { name: "about_us", resources: "pages"}%>

 <%= link_to 'Contact-Us' , contact_us_path  , style:'color:blue;'%>

 <%= link_to 'privacy', privacy_policy_path  , style:'color:blue;'%>

 <%= link_to 'T&C' , terms_conditions_path, target:'_blank'  , style:'color:blue;'%>

app/views/sports_news/index.html.erb
<div class="card rounded-0 mt-5 mb-5" >
    <div class="card-body">
       <h2 class="text-center">Sports details
        </h2>
     </div>   
</div>    


<div>
    <%= link_to 'Create Sports Details', new_sports_news_path ,class: "btn btn-primary btn-lg mb-5 rounded-0 text-center"%>
</div>
<table class="mt-5 ">
    <thead >
        <tr>
            <th>level</th>
            <th>authority</th>
            <th>mode</th>
        </tr>    
     </thead> 

     <tbody >
        <% @sports_news.each do |sports_new| %>

                <tr>
                    <td><%= sports_new.level%></td>
                    <td><%= sports_new.authority%></td>
                    <td><%= sports_new.mode%></td>
                </tr>   

        <% end %> 
        </tbody>  
</table>    

   

app/views/sports_news/new.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
        <h2 class="text-center">Create Sports Details</h2>
        </div>
    </div>

    <%= form_with model: @sports_news, local: true do |form| %>
        <div class="row">

            <div class="col-lg-4">
                <div class="form-group">
                <%= form.label :level, class: "mb-2" %>
                <%= form.text_field :level, class: "form-control form-control-lg rounded-0" %>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :authority, class: "mb-2"%>
                    <%= form.text_field :authority, class: "form-control form-control-lg rounded-0" %>
                </div>   
            </div>  

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :mode, class: "mb-2"%>
                    <%= form.text_field :mode, class: "form-control form-control-lg rounded-0" %>
                </div>   
            </div>   

        </div>


        <div class="row">

             <div class="col-lg-12 mt-5">
                    <div class="text-center">
                        <%= form.submit class:"btn btn-primary btn-lg rounded-0"%>
                        <%= link_to 'Back to Sports Details' ,  sports_news_index_path, class:"btn btn-outline-primary btn-lg rounded-0"%>
                    </div>
             </div>
        </div>   
    
    <% end %>
</div>